name: Release

on:
  release:
    types: [created, edited]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Package
      run: |
        make install PREFIX=linux-utils-x86_64
        tar cvvjf linux-utils-x86_64.tar.bz2 linux-utils-x86_64

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux-utils-x86_64.tar.bz2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
